<?php

function gmapfield_field_info() {
    return array(
        'gmapfield_location' => array(
            'label' => t('Google map'),
            'description' => t(
                'This field stores a location for google map'),
            'default_widget' => 'gmapfield_map',
            'default_formatter' => 'gmapfield_default',
        ),
    );
}

function gmapfield_field_schema($field) {
    if ($field['type'] == 'gmapfield_location') {
        $schema = array();
        $schema['columns']['lat'] = array(
            'type' => 'numeric',
            'precision' => 9,
            'scale' => 6,
        );
        $schema['columns']['lng'] = array(
            'type' => 'numeric',
            'precision' => 9,
            'scale' => 6,
        );
        $schema['columns']['zoom'] = array(
            'type' => 'int',
            'size' => 'tiny',
            'default' => 10,
        );

        return $schema;
    }
}

function gmapfield_field_is_empty($item, $field) {
    if ($field['type'] == 'gmapfield_location') {
        if (empty($item['lat']) || empty($item['lng'])) {
            return true;
        }
    }
    return false;
}

//
//  widget
//

function gmapfield_field_widget_info() {
    $widgets = array();
    $widgets['gmapfield_map'] = array(
        'label' => t('Google map'),
        'description' => t(
            'Allow the user choose location from Google map.'),
        'field types' => array('gmapfield_location'),
        'behaviors' => array(
            'multiple values' => FIELD_BEHAVIOR_DEFAULT,
            'default value' => FIELD_BEHAVIOR_DEFAULT,
        ),
    );
    return $widgets;
}

function gmapfield_field_widget_form(&$form, &$form_state, 
                                     $field, $instance, 
                                     $langcode, $items, 
                                     $delta, $element) {
    if ($instance['widget']['type'] == 'gmapfield_map') {
        dpm($items);
        $lat = isset($items[$delta]) ? $items[$delta]['lat'] : 31.231592;
        $lng = isset($items[$delta]) ? $items[$delta]['lng'] : 121.47171;
        $zoom = isset($items[$delta]) ? $items[$delta]['zoom'] : 10;
        $element['mapfield'] = array(
            '#type' => 'fieldset', 
            '#title' => t('Map settings'), 
            '#collapsible' => true, 
            '#collapsed' => true,
            '#attributes' => array(
                'id' => "gmapfield-edit-$delta"
            ),
        );
        $element['mapfield']['lat'] = array(
            '#type' => 'hidden',
            '#default_value' => $lat,
            '#parents' => array($element['#field_name'], 'und', $delta, 'lat'),
            '#attributes' => array(
                'class' => "gmapfield-lat"
            ),
        );
        $element['mapfield']['lng'] = array(
            '#type' => 'hidden',
            '#default_value' => $lng,
            '#parents' => array($element['#field_name'], 'und', $delta, 'lng'),
            '#attributes' => array(
                'class' => "gmapfield-lng"
            ),
        );
        $element['mapfield']['zoom'] = array(
            '#type' => 'hidden',
            '#default_value' => $zoom,
            '#parents' => array($element['#field_name'], 'und', $delta, 'zoom'),
            '#attributes' => array(
                'class' => "gmapfield-zoom"
            ),
        );
        $element['mapfield']['map_canvas'] = array(
            '#markup' => '<div class="gmapfield-map-canvas"></div>',
        );
        $element['#attached']['drupal_add_js'] = array(
            array(array(
                'gmapfields'=>array($delta),
            ), 'setting'),
        );
        $element['#attached']['js'] = array(
            'http://maps.google.com/maps/api/js?sensor=false' => array(
                'type' => 'external',
            ),
            drupal_get_path('module', 'gmapfield') . '/gmapfield.js',
        );
    }

    return $element;
}

//
//  formatter
//

function gmapfield_field_formatter_info() {
    return array(
        'gmapfield_default' => array(
            'label' => t('Default'),
            'field types' => array('gmapfield_location'),
        ),
    );
}

function gmapfield_field_formatter_view($entity_type, $entity, 
                                        $field, $instance, 
                                        $langcode, $items, $display) {
    switch ($display['type']) {
    case 'gmapfield_default':
        foreach ($items as $delta => $item) {
            $element[$delta] = array(
                '#markup' => $item['value'],
            );
        }
        break;
    }

    return $element;
}
